name: Mirror Helm Charts

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  mirror-redis-chart:
    uses: ./.github/workflows/mirror-helm-chart.yml
    with:
      chart_name: redis
      chart_version: "22.0.7"
      chart_repo_url: oci://registry-1.docker.io/bitnamicharts
      target_package: ${{ github.repository_owner }}/charts
    permissions:
      packages: write
      contents: read

  mirror-cloudpirates-postgres-chart:
    uses: ./.github/workflows/mirror-helm-chart.yml
    with:
      chart_name: postgres
      chart_version: "0.18.3"
      chart_repo_url: oci://registry-1.docker.io/cloudpirates
      target_package: ${{ github.repository_owner }}/charts
    permissions:
      packages: write
      contents: read

  mirror-cloudpirates-common-chart:
    uses: ./.github/workflows/mirror-helm-chart.yml
    with:
      chart_name: common
      chart_version: "2.2.0"
      chart_repo_url: oci://registry-1.docker.io/cloudpirates
      target_package: ${{ github.repository_owner }}/charts
    permissions:
      packages: write
      contents: read
